Repository KinsonDigital/BranchValidator, pull requests merged in 2023-08, with the labels that each got.

#112 🚧Adjust release workflow input
  .github/workflows/add-new-issue-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/unit-test-status-check.yml
Labels: low priority, ♻️cicd

#114 🚧Lock version of MOQ
  .github/workflows/add-new-issue-to-project.yml
  .github/workflows/sync-bot.yml
  README.md
  Testing/BranchValidatorTests/BranchValidatorTests.csproj
  Testing/ScriptGeneratorTests/ScriptGeneratorTests.csproj
  Testing/TestingShared/TestingShared.csproj
Labels: 📦dependency update, high priority

#116 🚧Adjust workflow trigger
  .github/workflows/add-new-issue-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/sync-bot.yml
  .github/workflows/sync-issue-to-pr.yml
  .github/workflows/sync-pr-to-issue.yml
  .github/workflows/sync-status-check.yml
  .github/workflows/unit-test-status-check.yml
Labels: high priority, preview, ♻️cicd
